var repos_data = [
  {
    name: ".scripts",
    description:
      "A collection of small scripts I use on my arch install instead of some other DE utils",
    html_url: "https://github.com/JakeRoggenbuck/.scripts",
    archived: false,
    stargazers_count: 0,
    language: "Shell",
    license: null,
    private: false,
  },
  {
    name: ".wallpaper",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/.wallpaper",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "advent-of-code",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/advent-of-code",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "amethyst",
    description: "A simple package manager written in ruby",
    html_url: "https://github.com/JakeRoggenbuck/amethyst",
    archived: false,
    stargazers_count: 0,
    language: "Ruby",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Apollo-11",
    description:
      "Original Apollo 11 Guidance Computer (AGC) source code for the command and lunar modules.",
    html_url: "https://github.com/JakeRoggenbuck/Apollo-11",
    archived: false,
    stargazers_count: 0,
    language: "Assembly",
    license: {
      key: "other",
      name: "Other",
      spdx_id: "NOASSERTION",
      url: null,
      node_id: "MDc6TGljZW5zZTA=",
    },
    private: false,
  },
  {
    name: "arch_installer",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/arch_installer",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "argos-translate",
    description:
      "Open source neural machine translation in Python. Designed to be used either as a Python library or desktop application. Uses OpenNMT for translations and PyQt for GUI.",
    html_url: "https://github.com/JakeRoggenbuck/argos-translate",
    archived: false,
    stargazers_count: 1,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "asmura",
    description: "An RPG game set in Vaskalli.",
    html_url: "https://github.com/JakeRoggenbuck/asmura",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "BackgroundImageText",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/BackgroundImageText",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "bash_startup",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/bash_startup",
    archived: false,
    stargazers_count: 0,
    language: "C++",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "BestVimPlugins",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/BestVimPlugins",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "bookmark-search",
    description:
      "A simple thing to allow you to search your bookmarks better than any browser default bookmark search",
    html_url: "https://github.com/JakeRoggenbuck/bookmark-search",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "BrainF",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/BrainF",
    archived: false,
    stargazers_count: 0,
    language: "Brainfuck",
    license: null,
    private: false,
  },
  {
    name: "break",
    description:
      "A simple build system that does the opposite to building,  irreversibly destroying your executables and source code according to your breakfile",
    html_url: "https://github.com/JakeRoggenbuck/break",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "bspswallow",
    description: "dwm-like swallowing for bspwm",
    html_url: "https://github.com/JakeRoggenbuck/bspswallow",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "calcLex",
    description: "A test of lexing and yacc in python",
    html_url: "https://github.com/JakeRoggenbuck/calcLex",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "CError",
    description:
      "Run cerror on a source code file of a compiled language to get the length of the outputted error compared to the filesize.",
    html_url: "https://github.com/JakeRoggenbuck/CError",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "ChatApp",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ChatApp",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "ChromeWebLauncher",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ChromeWebLauncher",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "claculator",
    description: "adds numbers together",
    html_url: "https://github.com/JakeRoggenbuck/claculator",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "wtfpl",
      name: "Do What The F*ck You Want To Public License",
      spdx_id: "WTFPL",
      url: "https://api.github.com/licenses/wtfpl",
      node_id: "MDc6TGljZW5zZTE4",
    },
    private: false,
  },
  {
    name: "cli",
    description: "GitHub\u2019s official command line tool",
    html_url: "https://github.com/JakeRoggenbuck/cli",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "codinggames",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/codinggames",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "colorgradient-rs",
    description: "Generate a gradient from selected colors",
    html_url: "https://github.com/JakeRoggenbuck/colorgradient-rs",
    archived: false,
    stargazers_count: 0,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Covid19-cases-tui",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Covid19-cases-tui",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "cruz-lang",
    description: "Cruz Lang is a simple explicit static typed language. ",
    html_url: "https://github.com/JakeRoggenbuck/cruz-lang",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Crypto-Chat",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Crypto-Chat",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "crystal-colord",
    description: "A library for colored text in crystal",
    html_url: "https://github.com/JakeRoggenbuck/crystal-colord",
    archived: false,
    stargazers_count: 0,
    language: "Crystal",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "dcbankofcarter",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/dcbankofcarter",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "Deepai",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Deepai",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Dictionary-tui",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Dictionary-tui",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "discord_keep_save",
    description: "Save important discord notes with keep save",
    html_url: "https://github.com/JakeRoggenbuck/discord_keep_save",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "dmenuSpecialCharacterCopier",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/dmenuSpecialCharacterCopier",
    archived: false,
    stargazers_count: 0,
    language: "Shell",
    license: null,
    private: false,
  },
  {
    name: "door-lock",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/door-lock",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "dotfiles",
    description:
      "A collection of my dotfiles that I use on my GNU/Linux machine",
    html_url: "https://github.com/JakeRoggenbuck/dotfiles",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: null,
    private: false,
  },
  {
    name: "dotfiles-1",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/dotfiles-1",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "dot_dropper",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/dot_dropper",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "draft.vim",
    description:
      "Quickly writeup and save drafts for messaging apps in your favorite editor",
    html_url: "https://github.com/JakeRoggenbuck/draft.vim",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "dwm",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/dwm",
    archived: false,
    stargazers_count: 0,
    language: "C",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "electronTBAViewer",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/electronTBAViewer",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: null,
    private: false,
  },
  {
    name: "f09f",
    description:
      "pronounced fonf; is a simple statically typed language with simple but powerful syntax",
    html_url: "https://github.com/JakeRoggenbuck/f09f",
    archived: false,
    stargazers_count: 2,
    language: "C++",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "f09f-rs",
    description:
      "pronounced fonf; is a statically typed language with simple but powerful syntax, and an interpreter written in rust",
    html_url: "https://github.com/JakeRoggenbuck/f09f-rs",
    archived: false,
    stargazers_count: 0,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "fastly-py",
    description: "Fastly Python Client",
    html_url: "https://github.com/JakeRoggenbuck/fastly-py",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "firefox-landing-page",
    description: "A simple landing page for firefox and searhing",
    html_url: "https://github.com/JakeRoggenbuck/firefox-landing-page",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "firefox-landing-page-1",
    description: "A simple epic landing page.",
    html_url: "https://github.com/JakeRoggenbuck/firefox-landing-page-1",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: null,
    private: false,
  },
  {
    name: "firefoxThemes",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/firefoxThemes",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "flask-sql-login",
    description:
      "SQL login page: If this is insecure please let me know so I can fix it",
    html_url: "https://github.com/JakeRoggenbuck/flask-sql-login",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "FlaskSQLApp",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/FlaskSQLApp",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "flowerknight",
    description:
      "A game we're making over the summer to present to the school at the Club Fair.",
    html_url: "https://github.com/JakeRoggenbuck/flowerknight",
    archived: false,
    stargazers_count: 0,
    language: "Java",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "fork-craft",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/fork-craft",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "fred",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/fred",
    archived: false,
    stargazers_count: 0,
    language: "Ruby",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "fumble_api",
    description:
      "A simple web API to return critical charts for the game dnd 5e",
    html_url: "https://github.com/JakeRoggenbuck/fumble_api",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "GalapagosReefOctopus",
    description: "Galapagos Reef Octopus",
    html_url: "https://github.com/JakeRoggenbuck/GalapagosReefOctopus",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "git-lesson",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/git-lesson",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "git-training",
    description: "Git(hub) training for Scouting Programmers",
    html_url: "https://github.com/JakeRoggenbuck/git-training",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "gnome-clocks",
    description: "Clocks applications for GNOME",
    html_url: "https://github.com/JakeRoggenbuck/gnome-clocks",
    archived: false,
    stargazers_count: 0,
    language: "Vala",
    license: {
      key: "gpl-2.0",
      name: "GNU General Public License v2.0",
      spdx_id: "GPL-2.0",
      url: "https://api.github.com/licenses/gpl-2.0",
      node_id: "MDc6TGljZW5zZTg=",
    },
    private: false,
  },
  {
    name: "GPGExchange",
    description:
      "Website for posting encrypted files, encrypted meme exchange.",
    html_url: "https://github.com/JakeRoggenbuck/GPGExchange",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "gpg_passkeep",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/gpg_passkeep",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "gpt-2",
    description:
      'Code for the paper "Language Models are Unsupervised Multitask Learners"',
    html_url: "https://github.com/JakeRoggenbuck/gpt-2",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "hash-colorer",
    description: "A small util to view hashes as color",
    html_url: "https://github.com/JakeRoggenbuck/hash-colorer",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "HexViewer",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/HexViewer",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "hexviewer-rs",
    description:
      "Hexviewer allows you to quickly view the hex representation of a file with vim style keybinds",
    html_url: "https://github.com/JakeRoggenbuck/hexviewer-rs",
    archived: false,
    stargazers_count: 1,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Highlight",
    description: "A simple social media website for sharing messages",
    html_url: "https://github.com/JakeRoggenbuck/Highlight",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "ice",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ice",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "ImgurApi",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ImgurApi",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "ImportLint",
    description:
      "Check and fix your module and package imports in python files",
    html_url: "https://github.com/JakeRoggenbuck/ImportLint",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "impulse",
    description: "A simple package manager.",
    html_url: "https://github.com/JakeRoggenbuck/impulse",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "inflector",
    description: "For our language",
    html_url: "https://github.com/JakeRoggenbuck/inflector",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "is_254_or_larger",
    description: "first test making an npm package, also a joke",
    html_url: "https://github.com/JakeRoggenbuck/is_254_or_larger",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: null,
    private: false,
  },
  {
    name: "jakeroggenbuck",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/jakeroggenbuck",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "JakeRoggenbuck.github.io",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/JakeRoggenbuck.github.io",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "jakesutils",
    description: "A collection of utils that I use all the time in my projects",
    html_url: "https://github.com/JakeRoggenbuck/jakesutils",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "JARBS",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/JARBS",
    archived: false,
    stargazers_count: 0,
    language: "Shell",
    license: null,
    private: false,
  },
  {
    name: "JavaPong",
    description: "pong in java",
    html_url: "https://github.com/JakeRoggenbuck/JavaPong",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "Journal.vim",
    description: "This vim plugin lets you organize your daily journal",
    html_url: "https://github.com/JakeRoggenbuck/Journal.vim",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "js-snake",
    description: "Snake game written in p5 JS",
    html_url: "https://github.com/JakeRoggenbuck/js-snake",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "kotlin-todo-app",
    description: "A simple kotlin hello world project from a tutorial",
    html_url: "https://github.com/JakeRoggenbuck/kotlin-todo-app",
    archived: false,
    stargazers_count: 0,
    language: "Kotlin",
    license: null,
    private: false,
  },
  {
    name: "Lan-Website",
    description: "php is not that scary",
    html_url: "https://github.com/JakeRoggenbuck/Lan-Website",
    archived: false,
    stargazers_count: 0,
    language: "PHP",
    license: null,
    private: false,
  },
  {
    name: "learn-planck",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/learn-planck",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "learningMachineLearning",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/learningMachineLearning",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "learningx86_assembly",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/learningx86_assembly",
    archived: false,
    stargazers_count: 0,
    language: "Assembly",
    license: null,
    private: false,
  },
  {
    name: "learning_sql",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/learning_sql",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "lightBot",
    description: "A Discord bot that controls my lights",
    html_url: "https://github.com/JakeRoggenbuck/lightBot",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "LimeOS",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/LimeOS",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "link",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/link",
    archived: false,
    stargazers_count: 0,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "markov-chain",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/markov-chain",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "mechanize",
    description: "The official source code for the python-mechanize project",
    html_url: "https://github.com/JakeRoggenbuck/mechanize",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "other",
      name: "Other",
      spdx_id: "NOASSERTION",
      url: null,
      node_id: "MDc6TGljZW5zZTA=",
    },
    private: false,
  },
  {
    name: "minecraft_texture_packs",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/minecraft_texture_packs",
    archived: false,
    stargazers_count: 0,
    language: "GLSL",
    license: null,
    private: false,
  },
  {
    name: "ModPackMaker",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ModPackMaker",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongo-notes",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/mongo-notes",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongoc",
    description:
      "A command line viewer for MongoDB. Quickly view documents, collections, and databases stored locally for easy debugging and system maintenance.",
    html_url: "https://github.com/JakeRoggenbuck/mongoc",
    archived: false,
    stargazers_count: 1,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongoc-rs",
    description:
      "Quickly view your mongodb databases, their collections, and their documents from the command line",
    html_url: "https://github.com/JakeRoggenbuck/mongoc-rs",
    archived: false,
    stargazers_count: 0,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "mongodb-login",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/mongodb-login",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongodb_schema_check",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/mongodb_schema_check",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongofastlogger",
    description:
      "A simple and fask logging library that uses the power of mongodb to save and query logs (with built in cli)",
    html_url: "https://github.com/JakeRoggenbuck/mongofastlogger",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "MongoShortener",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/MongoShortener",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "mongo_passkeep",
    description: "A command line utility for storing passwords",
    html_url: "https://github.com/JakeRoggenbuck/mongo_passkeep",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "n-rus-bot",
    description: "Discord bot for the e:b:ic server",
    html_url: "https://github.com/JakeRoggenbuck/n-rus-bot",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "nasa-spaceapps-2020",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/nasa-spaceapps-2020",
    archived: false,
    stargazers_count: 1,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "ned-bot",
    description:
      "A discord bot that reacts with \ud83c\udde9 when any users react with \ud83c\uddf3 and \ud83c\uddea. It likes spelling its name.",
    html_url: "https://github.com/JakeRoggenbuck/ned-bot",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "new-website",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/new-website",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "nitrogen-css",
    description:
      "A very epic CSS front end framework that is slightly not bad.",
    html_url: "https://github.com/JakeRoggenbuck/nitrogen-css",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "nxyso_api",
    description:
      "A definition and search API for a language called Nysjomon made using FastApi",
    html_url: "https://github.com/JakeRoggenbuck/nxyso_api",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "nxyso_definition_bot",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/nxyso_definition_bot",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "openpilot",
    description: "open source driving agent",
    html_url: "https://github.com/JakeRoggenbuck/openpilot",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Paper",
    description: "A simple programming language and its interpreter",
    html_url: "https://github.com/JakeRoggenbuck/Paper",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "pathfinder",
    description: "A simple utility to view, edit, and search your $PATH",
    html_url: "https://github.com/JakeRoggenbuck/pathfinder",
    archived: false,
    stargazers_count: 1,
    language: "Rust",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "pinter",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/pinter",
    archived: false,
    stargazers_count: 0,
    language: "C",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "planck.vim",
    description: "A syntax highlighting for planck lang files",
    html_url: "https://github.com/JakeRoggenbuck/planck.vim",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "player_data_finder",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/player_data_finder",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "pll",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/pll",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "pogscript",
    description: "A simple macro language",
    html_url: "https://github.com/JakeRoggenbuck/pogscript",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Polybot",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Polybot",
    archived: false,
    stargazers_count: 0,
    language: "C++",
    license: null,
    private: false,
  },
  {
    name: "Polybot-2",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Polybot-2",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "position_reader",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/position_reader",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "public-pgp-keys",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/public-pgp-keys",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "pwntools",
    description: "CTF framework and exploit development library",
    html_url: "https://github.com/JakeRoggenbuck/pwntools",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "other",
      name: "Other",
      spdx_id: "NOASSERTION",
      url: null,
      node_id: "MDc6TGljZW5zZTA=",
    },
    private: false,
  },
  {
    name: "pyswitch",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/pyswitch",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "qme-launcher",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/qme-launcher",
    archived: false,
    stargazers_count: 0,
    language: "Java",
    license: null,
    private: false,
  },
  {
    name: "qme-releases",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/qme-releases",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "qme5-server",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/qme5-server",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Reddit_Downloader",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Reddit_Downloader",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "reminder-bot",
    description: "A Discord Bot designed to remind users of custom events",
    html_url: "https://github.com/JakeRoggenbuck/reminder-bot",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "rocket-pinball",
    description: "Space themed pinball rework, with new game elements",
    html_url: "https://github.com/JakeRoggenbuck/rocket-pinball",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "rocky",
    description:
      "Rocky Linux is a community enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux created in response to the effective discontinuation of CentOS.",
    html_url: "https://github.com/JakeRoggenbuck/rocky",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "Route-Finding",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Route-Finding",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "RushNote",
    description: "Take quick notes from command line when in a rush.",
    html_url: "https://github.com/JakeRoggenbuck/RushNote",
    archived: false,
    stargazers_count: 0,
    language: "C++",
    license: null,
    private: false,
  },
  {
    name: "sapphire",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/sapphire",
    archived: false,
    stargazers_count: 0,
    language: "Ruby",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "SARS-CoV-2_Peplomer_Structure_Analysis",
    description: null,
    html_url:
      "https://github.com/JakeRoggenbuck/SARS-CoV-2_Peplomer_Structure_Analysis",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "scouting-scripts",
    description: "Holds miscellaneous scripts for Software Scouting",
    html_url: "https://github.com/JakeRoggenbuck/scouting-scripts",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Scry",
    description:
      "Scry is a web application that allows users to quickly check open ports, logins, and critical system information about their server from any web browser, anywhere.",
    html_url: "https://github.com/JakeRoggenbuck/Scry",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Seamonsters-2605.github.io",
    description: "Seamonsters team Github Pages site",
    html_url: "https://github.com/JakeRoggenbuck/Seamonsters-2605.github.io",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "server-public",
    description:
      "Data processing Python server that interfaces with collection and visualization apps in a FRC scouting system",
    html_url: "https://github.com/JakeRoggenbuck/server-public",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "sfetch",
    description: "A simple fetch for testing PKGBUILD",
    html_url: "https://github.com/JakeRoggenbuck/sfetch",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Shredder",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Shredder",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "SignInWebApp",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/SignInWebApp",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "Skyometer",
    description:
      "A website written in google app script and javascript using google sheets as a data collector",
    html_url: "https://github.com/JakeRoggenbuck/Skyometer",
    archived: false,
    stargazers_count: 0,
    language: "HTML",
    license: null,
    private: false,
  },
  {
    name: "snow_script",
    description:
      "A simple and high/low macro lang, similar to pogscript with way nicer syntax",
    html_url: "https://github.com/JakeRoggenbuck/snow_script",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "sodium",
    description: "Mirror of https://gitlab.redox-os.org/redox-os/sodium",
    html_url: "https://github.com/JakeRoggenbuck/sodium",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "SoftwareGeneralFinalTests",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/SoftwareGeneralFinalTests",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "sort-vis",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/sort-vis",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "spaceapp",
    description: "Telescope Aiming tool",
    html_url: "https://github.com/JakeRoggenbuck/spaceapp",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "spicetify-cli-extensions",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/spicetify-cli-extensions",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "spicetify-cli-themes",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/spicetify-cli-themes",
    archived: false,
    stargazers_count: 0,
    language: "CSS",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "spicetify-customapps",
    description:
      "A community-driven collection of custom apps for Spicetify (https://github.com/khanhas/spicetify-cli)",
    html_url: "https://github.com/JakeRoggenbuck/spicetify-customapps",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "spicetify-themes",
    description:
      "A community-driven collection of themes for Spicetify (https://github.com/khanhas/spicetify-cli)",
    html_url: "https://github.com/JakeRoggenbuck/spicetify-themes",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "SQLShortener",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/SQLShortener",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "strategy_presentation_numpy",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/strategy_presentation_numpy",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "tap",
    description: "Quickly tap basic file into existence",
    html_url: "https://github.com/JakeRoggenbuck/tap",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "tbaTestScripts",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/tbaTestScripts",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "Terbot-2",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Terbot-2",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "Termitebot",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/Termitebot",
    archived: false,
    stargazers_count: 0,
    language: "C++",
    license: null,
    private: false,
  },
  {
    name: "testDiscordBot",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/testDiscordBot",
    archived: false,
    stargazers_count: 0,
    language: "JavaScript",
    license: null,
    private: false,
  },
  {
    name: "tlib",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/tlib",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
  },
  {
    name: "typeschemalib",
    description:
      "A yaml like schema that can be used to check dictionaries for correct schema",
    html_url: "https://github.com/JakeRoggenbuck/typeschemalib",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "ursina",
    description: "A game engine powered by python and panda3d.",
    html_url: "https://github.com/JakeRoggenbuck/ursina",
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "ursina-platform-game",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/ursina-platform-game",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "valueourminds_website",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/valueourminds_website",
    archived: false,
    stargazers_count: 0,
    language: "CSS",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vim-character-creator",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/vim-character-creator",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vim-game-snake",
    description: "Vim Game : Snake",
    html_url: "https://github.com/JakeRoggenbuck/vim-game-snake",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vim-impulse-syntax",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/vim-impulse-syntax",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vim-selection-test",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/vim-selection-test",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vim-snow-script-syntax",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/vim-snow-script-syntax",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "vimage.vim",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/vimage.vim",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "Vorahk",
    description: "A bot that sends my spotify playlists to bots to play them",
    html_url: "https://github.com/JakeRoggenbuck/Vorahk",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "wallpaper_downloader",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/wallpaper_downloader",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "xdotool_python_window_util",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/xdotool_python_window_util",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "yaml_serialize",
    description: "A simple way to store python objects in yaml",
    html_url: "https://github.com/JakeRoggenbuck/yaml_serialize",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: null,
    private: false,
  },
  {
    name: "yes-no-neural-network-classifier",
    description: null,
    html_url:
      "https://github.com/JakeRoggenbuck/yes-no-neural-network-classifier",
    archived: false,
    stargazers_count: 0,
    language: "Python",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    private: false,
  },
  {
    name: "zerOS",
    description: "an os? based on arch",
    html_url: "https://github.com/JakeRoggenbuck/zerOS",
    archived: false,
    stargazers_count: 0,
    language: "Shell",
    license: null,
    private: false,
  },
  {
    name: "zflat",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/zflat",
    archived: false,
    stargazers_count: 0,
    language: "C++",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
  {
    name: "zflat.vim",
    description: null,
    html_url: "https://github.com/JakeRoggenbuck/zflat.vim",
    archived: false,
    stargazers_count: 0,
    language: "Vim script",
    license: {
      key: "gpl-3.0",
      name: "GNU General Public License v3.0",
      spdx_id: "GPL-3.0",
      url: "https://api.github.com/licenses/gpl-3.0",
      node_id: "MDc6TGljZW5zZTk=",
    },
    private: false,
  },
];

var projects_data = [
  {
    name: "QME Games",
    desc: "A game development group",
    url: "https://github.com/qmegame/",
  },
  {
    name: "DHS Gamedev",
    desc: "A game development club",
    url: "https://github.com/dhs-gamedev/",
  },
  {
    name: "DV-CSHS",
    desc: "The Da Vinci Computer Science website",
    url: "https://sites.google.com/djusdstudents.org/dv-cshs",
  },
];

var links_data = [
  {
    name: "Github",
    desc: "The place with all my public programming projects",
    url: "https://github.com/jakeroggenbuck",
  },
];

var tutoring_data = [
  {
    logo: "url",
    name: "Intro to python",
    description: "a description",
    grade_recommendation: "1st",
    prerequisites: ["python 1", "python 2"],
    times_available: ["day 1", "day 2"],
  },
];
