var repos_data = [
  {
    name: '.scripts',
    description:
      'A collection of small scripts I use on my arch install instead of some other DE utils',
    html_url: 'https://github.com/JakeRoggenbuck/.scripts',
    archived: false,
    stargazers_count: 0,
    language: 'Shell',
    license: null,
    private: false,
    created_at: 'October 31, 2019',
  },
  {
    name: '.wallpaper',
    description: 'A collection of wallpapers',
    html_url: 'https://github.com/JakeRoggenbuck/.wallpaper',
    archived: false,
    stargazers_count: 1,
    language: null,
    license: null,
    private: false,
    created_at: 'April 17, 2020',
  },
  {
    name: '2021-software-general-homework',
    description:
      'Master repository for Software General members to fork and clone in order to upload their lessons to Github',
    html_url:
      'https://github.com/JakeRoggenbuck/2021-software-general-homework',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'August 23, 2021',
  },
  {
    name: 'advent-of-code',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/advent-of-code',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'December 01, 2020',
  },
  {
    name: 'amethyst',
    description: 'A simple package manager written in ruby',
    html_url: 'https://github.com/JakeRoggenbuck/amethyst',
    archived: false,
    stargazers_count: 0,
    language: 'Ruby',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 14, 2020',
  },
  {
    name: 'Apollo-11',
    description:
      'Original Apollo 11 Guidance Computer (AGC) source code for the command and lunar modules.',
    html_url: 'https://github.com/JakeRoggenbuck/Apollo-11',
    archived: false,
    stargazers_count: 0,
    language: 'Assembly',
    license: {
      key: 'other',
      name: 'Other',
      spdx_id: 'NOASSERTION',
      url: null,
      node_id: 'MDc6TGljZW5zZTA=',
    },
    private: false,
    created_at: 'February 20, 2020',
  },
  {
    name: 'arch_installer',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/arch_installer',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 23, 2020',
  },
  {
    name: 'argos-translate',
    description:
      'Open source neural machine translation in Python. Designed to be used either as a Python library or desktop application. Uses OpenNMT for translations and PyQt for GUI.',
    html_url: 'https://github.com/JakeRoggenbuck/argos-translate',
    archived: false,
    stargazers_count: 1,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 21, 2021',
  },
  {
    name: 'asmura',
    description: 'An RPG game set in Vaskalli.',
    html_url: 'https://github.com/JakeRoggenbuck/asmura',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'March 24, 2020',
  },
  {
    name: 'auto-clock-speed',
    description:
      'A utility to check stats about your CPU, and auto regulate clock speeds to help with either performance or battery life.',
    html_url: 'https://github.com/JakeRoggenbuck/auto-clock-speed',
    archived: false,
    stargazers_count: 7,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 07, 2021',
  },
  {
    name: 'BackgroundImageText',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/BackgroundImageText',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'July 05, 2019',
  },
  {
    name: 'bash_startup',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/bash_startup',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'January 29, 2021',
  },
  {
    name: 'BestVimPlugins',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/BestVimPlugins',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'October 26, 2020',
  },
  {
    name: 'bookmark-search',
    description:
      'A simple thing to allow you to search your bookmarks better than any browser default bookmark search',
    html_url: 'https://github.com/JakeRoggenbuck/bookmark-search',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'February 22, 2021',
  },
  {
    name: 'BrainF',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/BrainF',
    archived: false,
    stargazers_count: 0,
    language: 'Brainfuck',
    license: null,
    private: false,
    created_at: 'March 16, 2020',
  },
  {
    name: 'break',
    description:
      'A simple build system that does the opposite to building,  irreversibly destroying your executables and source code according to your breakfile',
    html_url: 'https://github.com/JakeRoggenbuck/break',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'June 24, 2020',
  },
  {
    name: 'bspswallow',
    description: 'dwm-like swallowing for bspwm',
    html_url: 'https://github.com/JakeRoggenbuck/bspswallow',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 01, 2020',
  },
  {
    name: 'calcLex',
    description: 'A test of lexing and yacc in python',
    html_url: 'https://github.com/JakeRoggenbuck/calcLex',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'April 24, 2020',
  },
  {
    name: 'Cardinal',
    description:
      'Cardinal is a web server that serves data from the frc1678/server project to the frc1678/viewer project.',
    html_url: 'https://github.com/JakeRoggenbuck/Cardinal',
    archived: false,
    stargazers_count: 3,
    language: 'Python',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'September 16, 2021',
  },
  {
    name: 'CError',
    description:
      'Run cerror on a source code file of a compiled language to get the length of the outputted error compared to the filesize.',
    html_url: 'https://github.com/JakeRoggenbuck/CError',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 10, 2020',
  },
  {
    name: 'ChatApp',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ChatApp',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 17, 2020',
  },
  {
    name: 'ChromeWebLauncher',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ChromeWebLauncher',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'January 20, 2019',
  },
  {
    name: 'claculator',
    description: 'adds numbers together',
    html_url: 'https://github.com/JakeRoggenbuck/claculator',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'wtfpl',
      name: 'Do What The F*ck You Want To Public License',
      spdx_id: 'WTFPL',
      url: 'https://api.github.com/licenses/wtfpl',
      node_id: 'MDc6TGljZW5zZTE4',
    },
    private: false,
    created_at: 'May 23, 2020',
  },
  {
    name: 'cli',
    description: 'GitHub\u2019s official command line tool',
    html_url: 'https://github.com/JakeRoggenbuck/cli',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 19, 2020',
  },
  {
    name: 'Clifford',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Clifford',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: null,
    private: false,
    created_at: 'June 30, 2021',
  },
  {
    name: 'codinggames',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/codinggames',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'December 23, 2019',
  },
  {
    name: 'colorgradient',
    description: 'A tool to generate gradients in python',
    html_url: 'https://github.com/JakeRoggenbuck/colorgradient',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'February 20, 2021',
  },
  {
    name: 'colorgradient-julia',
    description: 'A tool in Julia to make color gradients',
    html_url: 'https://github.com/JakeRoggenbuck/colorgradient-julia',
    archived: false,
    stargazers_count: 0,
    language: 'Julia',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 14, 2021',
  },
  {
    name: 'colorgradient-rs',
    description: 'Generate a gradient from selected colors',
    html_url: 'https://github.com/JakeRoggenbuck/colorgradient-rs',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'May 01, 2021',
  },
  {
    name: 'Covid19-cases-tui',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Covid19-cases-tui',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 20, 2020',
  },
  {
    name: 'cproc',
    description: 'A small C preprocessor, written in C.',
    html_url: 'https://github.com/JakeRoggenbuck/cproc',
    archived: false,
    stargazers_count: 0,
    language: 'C',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'July 04, 2021',
  },
  {
    name: 'cpython',
    description: 'The Python programming language',
    html_url: 'https://github.com/JakeRoggenbuck/cpython',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'other',
      name: 'Other',
      spdx_id: 'NOASSERTION',
      url: null,
      node_id: 'MDc6TGljZW5zZTA=',
    },
    private: false,
    created_at: 'August 31, 2021',
  },
  {
    name: 'cruz-lang',
    description: 'Cruz Lang is a simple explicit static typed language. ',
    html_url: 'https://github.com/JakeRoggenbuck/cruz-lang',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 26, 2020',
  },
  {
    name: 'Crypto-Chat',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Crypto-Chat',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'January 25, 2020',
  },
  {
    name: 'crystal-colord',
    description: 'A library for colored text in crystal',
    html_url: 'https://github.com/JakeRoggenbuck/crystal-colord',
    archived: false,
    stargazers_count: 0,
    language: 'Crystal',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'January 30, 2021',
  },
  {
    name: 'cutil',
    description: 'Some shell commands written in C',
    html_url: 'https://github.com/JakeRoggenbuck/cutil',
    archived: false,
    stargazers_count: 0,
    language: 'C',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'July 20, 2021',
  },
  {
    name: 'dcbankofcarter',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/dcbankofcarter',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'May 03, 2019',
  },
  {
    name: 'Deepai',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Deepai',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 11, 2020',
  },
  {
    name: 'Dictionary-tui',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Dictionary-tui',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 19, 2020',
  },
  {
    name: 'discord_keep_save',
    description: 'Save important discord notes with keep save',
    html_url: 'https://github.com/JakeRoggenbuck/discord_keep_save',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 05, 2020',
  },
  {
    name: 'dmenuSpecialCharacterCopier',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/dmenuSpecialCharacterCopier',
    archived: false,
    stargazers_count: 0,
    language: 'Shell',
    license: null,
    private: false,
    created_at: 'March 19, 2020',
  },
  {
    name: 'door-lock',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/door-lock',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'December 11, 2020',
  },
  {
    name: 'dotfiles',
    description:
      'A collection of my dotfiles that I use on my GNU/Linux machine',
    html_url: 'https://github.com/JakeRoggenbuck/dotfiles',
    archived: false,
    stargazers_count: 0,
    language: 'Shell',
    license: null,
    private: false,
    created_at: 'September 12, 2020',
  },
  {
    name: 'dotfiles-1',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/dotfiles-1',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'August 04, 2020',
  },
  {
    name: 'dot_dropper',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/dot_dropper',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 26, 2020',
  },
  {
    name: 'draft.vim',
    description:
      'Quickly writeup and save drafts for messaging apps in your favorite editor. Save notes, code examples, or homework assignments.',
    html_url: 'https://github.com/JakeRoggenbuck/draft.vim',
    archived: false,
    stargazers_count: 1,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'December 31, 2020',
  },
  {
    name: 'dragon',
    description: 'Drag and drop source/target for X',
    html_url: 'https://github.com/JakeRoggenbuck/dragon',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'August 08, 2021',
  },
  {
    name: 'dwm',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/dwm',
    archived: false,
    stargazers_count: 0,
    language: 'C',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 20, 2020',
  },
  {
    name: 'electronTBAViewer',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/electronTBAViewer',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'April 03, 2020',
  },
  {
    name: 'EO-2021',
    description:
      'Solution for Earth Observing Dashboard 2021 Urban Societal Behavior Patterns Challenge',
    html_url: 'https://github.com/JakeRoggenbuck/EO-2021',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'June 26, 2021',
  },
  {
    name: 'f09f',
    description:
      'pronounced fonf; is a simple statically typed language with simple but powerful syntax',
    html_url: 'https://github.com/JakeRoggenbuck/f09f',
    archived: false,
    stargazers_count: 2,
    language: 'C++',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'March 11, 2021',
  },
  {
    name: 'f09f-rs',
    description:
      'pronounced fonf; is a statically typed language with simple but powerful syntax, and an interpreter written in rust',
    html_url: 'https://github.com/JakeRoggenbuck/f09f-rs',
    archived: false,
    stargazers_count: 1,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 22, 2021',
  },
  {
    name: 'fastly-py',
    description: 'Fastly Python Client',
    html_url: 'https://github.com/JakeRoggenbuck/fastly-py',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'October 06, 2020',
  },
  {
    name: 'firefox-landing-page',
    description: 'A simple landing page for firefox and searhing',
    html_url: 'https://github.com/JakeRoggenbuck/firefox-landing-page',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'April 23, 2020',
  },
  {
    name: 'firefox-landing-page-1',
    description: 'A simple epic landing page.',
    html_url: 'https://github.com/JakeRoggenbuck/firefox-landing-page-1',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'May 20, 2020',
  },
  {
    name: 'firefoxThemes',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/firefoxThemes',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'March 17, 2020',
  },
  {
    name: 'flask-sql-login',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/flask-sql-login',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 21, 2020',
  },
  {
    name: 'FlaskSQLApp',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/FlaskSQLApp',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 09, 2020',
  },
  {
    name: 'flowerknight',
    description:
      "A game we're making over the summer to present to the school at the Club Fair.",
    html_url: 'https://github.com/JakeRoggenbuck/flowerknight',
    archived: false,
    stargazers_count: 0,
    language: 'Java',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'June 01, 2021',
  },
  {
    name: 'fork-craft',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/fork-craft',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'March 21, 2020',
  },
  {
    name: 'fred',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/fred',
    archived: false,
    stargazers_count: 0,
    language: 'Ruby',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'July 10, 2020',
  },
  {
    name: 'fumble_api',
    description:
      'A simple web API to return critical charts for the game dnd 5e',
    html_url: 'https://github.com/JakeRoggenbuck/fumble_api',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 26, 2020',
  },
  {
    name: 'GalapagosReefOctopus',
    description: 'Galapagos Reef Octopus',
    html_url: 'https://github.com/JakeRoggenbuck/GalapagosReefOctopus',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'February 19, 2019',
  },
  {
    name: 'game-2021',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/game-2021',
    archived: false,
    stargazers_count: 0,
    language: 'C',
    license: null,
    private: false,
    created_at: 'October 08, 2021',
  },
  {
    name: 'game-design-scoring',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/game-design-scoring',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'February 06, 2021',
  },
  {
    name: 'git-lesson',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/git-lesson',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'November 08, 2019',
  },
  {
    name: 'git-training',
    description: 'Git(hub) training for Scouting Programmers',
    html_url: 'https://github.com/JakeRoggenbuck/git-training',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'January 02, 2019',
  },
  {
    name: 'gnome-clocks',
    description: 'Clocks applications for GNOME',
    html_url: 'https://github.com/JakeRoggenbuck/gnome-clocks',
    archived: false,
    stargazers_count: 0,
    language: 'Vala',
    license: {
      key: 'gpl-2.0',
      name: 'GNU General Public License v2.0',
      spdx_id: 'GPL-2.0',
      url: 'https://api.github.com/licenses/gpl-2.0',
      node_id: 'MDc6TGljZW5zZTg=',
    },
    private: false,
    created_at: 'July 03, 2019',
  },
  {
    name: 'GPGExchange',
    description:
      'Website for posting encrypted files, encrypted meme exchange.',
    html_url: 'https://github.com/JakeRoggenbuck/GPGExchange',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 18, 2020',
  },
  {
    name: 'gpg_passkeep',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/gpg_passkeep',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 03, 2020',
  },
  {
    name: 'gpt-2',
    description:
      'Code for the paper "Language Models are Unsupervised Multitask Learners"',
    html_url: 'https://github.com/JakeRoggenbuck/gpt-2',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'June 25, 2019',
  },
  {
    name: 'hash-colorer',
    description: 'A small util to view hashes as color',
    html_url: 'https://github.com/JakeRoggenbuck/hash-colorer',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'April 17, 2020',
  },
  {
    name: 'HexViewer',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/HexViewer',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'November 29, 2020',
  },
  {
    name: 'hexviewer-rs',
    description:
      'Hexviewer allows you to quickly view the hex representation of a file with vim style keybinds',
    html_url: 'https://github.com/JakeRoggenbuck/hexviewer-rs',
    archived: false,
    stargazers_count: 1,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'May 04, 2021',
  },
  {
    name: 'Highlight',
    description: 'A simple social media website for sharing messages',
    html_url: 'https://github.com/JakeRoggenbuck/Highlight',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'July 25, 2019',
  },
  {
    name: 'ice',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ice',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'October 06, 2020',
  },
  {
    name: 'ImgurApi',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ImgurApi',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 29, 2020',
  },
  {
    name: 'ImportLint',
    description:
      'Check and fix your module and package imports in python files',
    html_url: 'https://github.com/JakeRoggenbuck/ImportLint',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'November 08, 2020',
  },
  {
    name: 'impulse',
    description: 'A simple package manager.',
    html_url: 'https://github.com/JakeRoggenbuck/impulse',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'April 17, 2020',
  },
  {
    name: 'inflector',
    description: 'For our language',
    html_url: 'https://github.com/JakeRoggenbuck/inflector',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'November 15, 2019',
  },
  {
    name: 'is_254_or_larger',
    description: 'first test making an npm package, also a joke',
    html_url: 'https://github.com/JakeRoggenbuck/is_254_or_larger',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'June 14, 2020',
  },
  {
    name: 'jai',
    description: ' Jai is a programming language',
    html_url: 'https://github.com/JakeRoggenbuck/jai',
    archived: false,
    stargazers_count: 3,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 20, 2021',
  },
  {
    name: 'jakeroggenbuck',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/jakeroggenbuck',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'April 01, 2021',
  },
  {
    name: 'JakeRoggenbuck.github.io',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/JakeRoggenbuck.github.io',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'May 27, 2019',
  },
  {
    name: 'jakesutils',
    description: 'A collection of utils that I use all the time in my projects',
    html_url: 'https://github.com/JakeRoggenbuck/jakesutils',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'November 07, 2020',
  },
  {
    name: 'jam0001',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/jam0001',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'August 20, 2021',
  },
  {
    name: 'JARBS',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/JARBS',
    archived: false,
    stargazers_count: 0,
    language: 'Shell',
    license: null,
    private: false,
    created_at: 'November 03, 2019',
  },
  {
    name: 'JavaPong',
    description: 'pong in java',
    html_url: 'https://github.com/JakeRoggenbuck/JavaPong',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'March 16, 2020',
  },
  {
    name: 'Journal.vim',
    description: 'This vim plugin lets you organize your daily journal',
    html_url: 'https://github.com/JakeRoggenbuck/Journal.vim',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'March 31, 2021',
  },
  {
    name: 'js-snake',
    description: 'Snake game written in p5 JS',
    html_url: 'https://github.com/JakeRoggenbuck/js-snake',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 18, 2020',
  },
  {
    name: 'kotlin-todo-app',
    description: 'A simple kotlin hello world project from a tutorial',
    html_url: 'https://github.com/JakeRoggenbuck/kotlin-todo-app',
    archived: false,
    stargazers_count: 0,
    language: 'Kotlin',
    license: null,
    private: false,
    created_at: 'February 15, 2021',
  },
  {
    name: 'Lan-Website',
    description: 'php is not that scary',
    html_url: 'https://github.com/JakeRoggenbuck/Lan-Website',
    archived: false,
    stargazers_count: 0,
    language: 'PHP',
    license: null,
    private: false,
    created_at: 'March 17, 2020',
  },
  {
    name: 'learn-planck',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/learn-planck',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'November 24, 2020',
  },
  {
    name: 'learningMachineLearning',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/learningMachineLearning',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 19, 2020',
  },
  {
    name: 'learningx86_assembly',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/learningx86_assembly',
    archived: false,
    stargazers_count: 0,
    language: 'Assembly',
    license: null,
    private: false,
    created_at: 'August 08, 2020',
  },
  {
    name: 'learning_sql',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/learning_sql',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 04, 2020',
  },
  {
    name: 'least-squares-regression',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/least-squares-regression',
    archived: false,
    stargazers_count: 0,
    language: 'Jupyter Notebook',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 17, 2021',
  },
  {
    name: 'lesson-tester',
    description:
      'Test python code in the browser. Wrap code with specific lesson tests for code completeness grading. ',
    html_url: 'https://github.com/JakeRoggenbuck/lesson-tester',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 27, 2021',
  },
  {
    name: 'lightBot',
    description: 'A Discord bot that controls my lights',
    html_url: 'https://github.com/JakeRoggenbuck/lightBot',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'May 27, 2020',
  },
  {
    name: 'LimeOS',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/LimeOS',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'October 31, 2019',
  },
  {
    name: 'link',
    description:
      'I url shortener using Rocket.rs & Diesel.rs; being used in production',
    html_url: 'https://github.com/JakeRoggenbuck/link',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'May 26, 2021',
  },
  {
    name: 'magic-identify',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/magic-identify',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 08, 2021',
  },
  {
    name: 'mahou',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/mahou',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: null,
    private: false,
    created_at: 'May 20, 2021',
  },
  {
    name: 'markov-chain',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/markov-chain',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 12, 2021',
  },
  {
    name: 'math',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/math',
    archived: false,
    stargazers_count: 0,
    language: 'Jupyter Notebook',
    license: null,
    private: false,
    created_at: 'September 04, 2021',
  },
  {
    name: 'mechanize',
    description: 'The official source code for the python-mechanize project',
    html_url: 'https://github.com/JakeRoggenbuck/mechanize',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'other',
      name: 'Other',
      spdx_id: 'NOASSERTION',
      url: null,
      node_id: 'MDc6TGljZW5zZTA=',
    },
    private: false,
    created_at: 'September 17, 2020',
  },
  {
    name: 'MeditativeSquares',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/MeditativeSquares',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'August 07, 2021',
  },
  {
    name: 'minecraft_texture_packs',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/minecraft_texture_packs',
    archived: false,
    stargazers_count: 0,
    language: 'GLSL',
    license: null,
    private: false,
    created_at: 'February 24, 2021',
  },
  {
    name: 'ModPackMaker',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ModPackMaker',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 09, 2020',
  },
  {
    name: 'mongo-notes',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/mongo-notes',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 10, 2020',
  },
  {
    name: 'mongoc',
    description:
      'A command line viewer for MongoDB. Quickly view documents, collections, and databases stored locally for easy debugging and system maintenance.',
    html_url: 'https://github.com/JakeRoggenbuck/mongoc',
    archived: false,
    stargazers_count: 1,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 24, 2020',
  },
  {
    name: 'mongoc-rs',
    description:
      'Quickly view your mongodb databases, their collections, and their documents from the command line',
    html_url: 'https://github.com/JakeRoggenbuck/mongoc-rs',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'May 09, 2021',
  },
  {
    name: 'mongodb-login',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/mongodb-login',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 05, 2020',
  },
  {
    name: 'mongodb_schema_check',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/mongodb_schema_check',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 23, 2020',
  },
  {
    name: 'mongofastlogger',
    description:
      'A simple and fask logging library that uses the power of mongodb to save and query logs (with built in cli)',
    html_url: 'https://github.com/JakeRoggenbuck/mongofastlogger',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 27, 2020',
  },
  {
    name: 'MongoShortener',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/MongoShortener',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 14, 2020',
  },
  {
    name: 'mongo_passkeep',
    description: 'A command line utility for storing passwords',
    html_url: 'https://github.com/JakeRoggenbuck/mongo_passkeep',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 16, 2020',
  },
  {
    name: 'my-readme-image',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/my-readme-image',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'June 30, 2021',
  },
  {
    name: 'n-rus-bot',
    description: 'Discord bot for the e:b:ic server',
    html_url: 'https://github.com/JakeRoggenbuck/n-rus-bot',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 16, 2020',
  },
  {
    name: 'nasa-spaceapps-2020',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/nasa-spaceapps-2020',
    archived: false,
    stargazers_count: 1,
    language: null,
    license: null,
    private: false,
    created_at: 'October 06, 2020',
  },
  {
    name: 'nasa-spaceapps-2021',
    description: 'Project for NASA Spaceapps 2021',
    html_url: 'https://github.com/JakeRoggenbuck/nasa-spaceapps-2021',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'October 02, 2021',
  },
  {
    name: 'ned-bot',
    description:
      'A discord bot that reacts with \ud83c\udde9 when any users react with \ud83c\uddf3 and \ud83c\uddea. It likes spelling its name.',
    html_url: 'https://github.com/JakeRoggenbuck/ned-bot',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 07, 2020',
  },
  {
    name: 'new-website',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/new-website',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'June 15, 2020',
  },
  {
    name: 'nitrogen-css',
    description:
      'A very epic CSS front end framework that is slightly not bad.',
    html_url: 'https://github.com/JakeRoggenbuck/nitrogen-css',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'March 31, 2021',
  },
  {
    name: 'novus-chart',
    description:
      'A modern looking, accessible medical chart application based on a MERN stack.',
    html_url: 'https://github.com/JakeRoggenbuck/novus-chart',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'June 30, 2021',
  },
  {
    name: 'nxyso_api',
    description:
      'A definition and search API for a language called Nysjomon made using FastApi',
    html_url: 'https://github.com/JakeRoggenbuck/nxyso_api',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 12, 2020',
  },
  {
    name: 'nxyso_definition_bot',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/nxyso_definition_bot',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'June 24, 2020',
  },
  {
    name: 'openpilot',
    description: 'open source driving agent',
    html_url: 'https://github.com/JakeRoggenbuck/openpilot',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'February 27, 2020',
  },
  {
    name: 'Paper',
    description: 'A simple programming language and its interpreter',
    html_url: 'https://github.com/JakeRoggenbuck/Paper',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'January 19, 2021',
  },
  {
    name: 'pathfinder',
    description: 'A simple utility to view, edit, and search your $PATH',
    html_url: 'https://github.com/JakeRoggenbuck/pathfinder',
    archived: false,
    stargazers_count: 1,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'May 06, 2021',
  },
  {
    name: 'pinter',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/pinter',
    archived: false,
    stargazers_count: 0,
    language: 'C',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'November 24, 2020',
  },
  {
    name: 'planck.vim',
    description: 'A syntax highlighting for planck lang files',
    html_url: 'https://github.com/JakeRoggenbuck/planck.vim',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'November 30, 2020',
  },
  {
    name: 'player_data_finder',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/player_data_finder',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 19, 2020',
  },
  {
    name: 'pll',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/pll',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'December 01, 2020',
  },
  {
    name: 'plrs',
    description:
      'The multi-tool of lexical analysis and tokenization. Make parsers in less time for many use cases.',
    html_url: 'https://github.com/JakeRoggenbuck/plrs',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 29, 2021',
  },
  {
    name: 'pogscript',
    description: 'A simple macro language',
    html_url: 'https://github.com/JakeRoggenbuck/pogscript',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'December 31, 2019',
  },
  {
    name: 'Polybot',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Polybot',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: null,
    private: false,
    created_at: 'December 18, 2019',
  },
  {
    name: 'Polybot-2',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Polybot-2',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'April 04, 2020',
  },
  {
    name: 'ponyc',
    description:
      ':horse: Pony is an open-source, actor-model, capabilities-secure, high performance programming language',
    html_url: 'https://github.com/JakeRoggenbuck/ponyc',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'bsd-2-clause',
      name: 'BSD 2-Clause "Simplified" License',
      spdx_id: 'BSD-2-Clause',
      url: 'https://api.github.com/licenses/bsd-2-clause',
      node_id: 'MDc6TGljZW5zZTQ=',
    },
    private: false,
    created_at: 'September 01, 2021',
  },
  {
    name: 'position_reader',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/position_reader',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 17, 2020',
  },
  {
    name: 'programming-languages',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/programming-languages',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'August 28, 2021',
  },
  {
    name: 'project-announcements',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/project-announcements',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 11, 2021',
  },
  {
    name: 'public-pgp-keys',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/public-pgp-keys',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'July 10, 2020',
  },
  {
    name: 'pwntools',
    description: 'CTF framework and exploit development library',
    html_url: 'https://github.com/JakeRoggenbuck/pwntools',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'other',
      name: 'Other',
      spdx_id: 'NOASSERTION',
      url: null,
      node_id: 'MDc6TGljZW5zZTA=',
    },
    private: false,
    created_at: 'January 12, 2020',
  },
  {
    name: 'pylexlite',
    description: 'A test of the early stages of plrs',
    html_url: 'https://github.com/JakeRoggenbuck/pylexlite',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 18, 2021',
  },
  {
    name: 'pyswitch',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/pyswitch',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 11, 2020',
  },
  {
    name: 'pytest_assignments',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/pytest_assignments',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'September 18, 2021',
  },
  {
    name: 'qme',
    description: 'A game written in Java',
    html_url: 'https://github.com/JakeRoggenbuck/qme',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'July 05, 2021',
  },
  {
    name: 'qme-launcher',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/qme-launcher',
    archived: false,
    stargazers_count: 0,
    language: 'Java',
    license: null,
    private: false,
    created_at: 'February 02, 2021',
  },
  {
    name: 'qme-releases',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/qme-releases',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'February 01, 2021',
  },
  {
    name: 'qme5-server',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/qme5-server',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'January 21, 2021',
  },
  {
    name: 'Reddit_Downloader',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Reddit_Downloader',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 11, 2020',
  },
  {
    name: 'reminder-bot',
    description: 'A Discord Bot designed to remind users of custom events',
    html_url: 'https://github.com/JakeRoggenbuck/reminder-bot',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'January 02, 2021',
  },
  {
    name: 'rock',
    description:
      'A simple command line utility for manipulating standard in and out, similar to awk',
    html_url: 'https://github.com/JakeRoggenbuck/rock',
    archived: false,
    stargazers_count: 0,
    language: 'Rust',
    license: null,
    private: false,
    created_at: 'May 17, 2021',
  },
  {
    name: 'rocket-pinball',
    description: 'Space themed pinball rework, with new game elements',
    html_url: 'https://github.com/JakeRoggenbuck/rocket-pinball',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 27, 2021',
  },
  {
    name: 'rocky',
    description:
      'Rocky Linux is a community enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux created in response to the effective discontinuation of CentOS.',
    html_url: 'https://github.com/JakeRoggenbuck/rocky',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'December 14, 2020',
  },
  {
    name: 'Route-Finding',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Route-Finding',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 24, 2020',
  },
  {
    name: 'RushNote',
    description: 'Take quick notes from command line when in a rush.',
    html_url: 'https://github.com/JakeRoggenbuck/RushNote',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: null,
    private: false,
    created_at: 'November 23, 2019',
  },
  {
    name: 'sapphire',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/sapphire',
    archived: false,
    stargazers_count: 0,
    language: 'Ruby',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 20, 2020',
  },
  {
    name: 'SARS-CoV-2_Peplomer_Structure_Analysis',
    description: null,
    html_url:
      'https://github.com/JakeRoggenbuck/SARS-CoV-2_Peplomer_Structure_Analysis',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 14, 2020',
  },
  {
    name: 'scouting-scripts',
    description: 'Holds miscellaneous scripts for Software Scouting',
    html_url: 'https://github.com/JakeRoggenbuck/scouting-scripts',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'February 17, 2020',
  },
  {
    name: 'Scry',
    description:
      'Scry is a web application that allows users to quickly check open ports, logins, and critical system information about their server from any web browser, anywhere.',
    html_url: 'https://github.com/JakeRoggenbuck/Scry',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'February 15, 2021',
  },
  {
    name: 'Seamonsters-2605.github.io',
    description: 'Seamonsters team Github Pages site',
    html_url: 'https://github.com/JakeRoggenbuck/Seamonsters-2605.github.io',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'November 05, 2019',
  },
  {
    name: 'server-public',
    description:
      'Data processing Python server that interfaces with collection and visualization apps in a FRC scouting system',
    html_url: 'https://github.com/JakeRoggenbuck/server-public',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'April 15, 2020',
  },
  {
    name: 'sfetch',
    description: 'A simple fetch for testing PKGBUILD',
    html_url: 'https://github.com/JakeRoggenbuck/sfetch',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 22, 2020',
  },
  {
    name: 'Shredder',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Shredder',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 07, 2020',
  },
  {
    name: 'Shuzhengz',
    description: 'Profile Readme Repo',
    html_url: 'https://github.com/JakeRoggenbuck/Shuzhengz',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'September 02, 2021',
  },
  {
    name: 'SignInWebApp',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/SignInWebApp',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'May 15, 2019',
  },
  {
    name: 'Skyometer',
    description:
      'A website written in google app script and javascript using google sheets as a data collector',
    html_url: 'https://github.com/JakeRoggenbuck/Skyometer',
    archived: false,
    stargazers_count: 0,
    language: 'HTML',
    license: null,
    private: false,
    created_at: 'September 03, 2019',
  },
  {
    name: 'snow_script',
    description:
      'A simple and high/low macro lang, similar to pogscript with way nicer syntax',
    html_url: 'https://github.com/JakeRoggenbuck/snow_script',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'June 19, 2020',
  },
  {
    name: 'sodium',
    description: 'Mirror of https://gitlab.redox-os.org/redox-os/sodium',
    html_url: 'https://github.com/JakeRoggenbuck/sodium',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'December 27, 2019',
  },
  {
    name: 'SoftwareGeneralFinalTests',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/SoftwareGeneralFinalTests',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 25, 2020',
  },
  {
    name: 'sort-vis',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/sort-vis',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'March 29, 2020',
  },
  {
    name: 'sorting-algorithms',
    description:
      'This repository contains a variety of sorting algorithms written in several programming languages.',
    html_url: 'https://github.com/JakeRoggenbuck/sorting-algorithms',
    archived: false,
    stargazers_count: 0,
    language: 'Java',
    license: null,
    private: false,
    created_at: 'June 29, 2021',
  },
  {
    name: 'spaceapp',
    description: 'Telescope Aiming tool',
    html_url: 'https://github.com/JakeRoggenbuck/spaceapp',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'June 24, 2019',
  },
  {
    name: 'spicetify-cli-extensions',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/spicetify-cli-extensions',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'November 26, 2020',
  },
  {
    name: 'spicetify-cli-themes',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/spicetify-cli-themes',
    archived: false,
    stargazers_count: 0,
    language: 'CSS',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'November 26, 2020',
  },
  {
    name: 'spicetify-customapps',
    description:
      'A community-driven collection of custom apps for Spicetify (https://github.com/khanhas/spicetify-cli)',
    html_url: 'https://github.com/JakeRoggenbuck/spicetify-customapps',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'January 18, 2021',
  },
  {
    name: 'spicetify-themes',
    description:
      'A community-driven collection of themes for Spicetify (https://github.com/khanhas/spicetify-cli)',
    html_url: 'https://github.com/JakeRoggenbuck/spicetify-themes',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'March 28, 2021',
  },
  {
    name: 'SQLShortener',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/SQLShortener',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 10, 2020',
  },
  {
    name: 'stow-squid',
    description: 'stow-squid - Stow your dotfiles',
    html_url: 'https://github.com/JakeRoggenbuck/stow-squid',
    archived: false,
    stargazers_count: 3,
    language: 'Rust',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 13, 2021',
  },
  {
    name: 'strategy_presentation_numpy',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/strategy_presentation_numpy',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'October 18, 2020',
  },
  {
    name: 'tap',
    description: 'Quickly tap basic file into existence',
    html_url: 'https://github.com/JakeRoggenbuck/tap',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'August 29, 2020',
  },
  {
    name: 'tbaTestScripts',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/tbaTestScripts',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 16, 2020',
  },
  {
    name: 'Terbot-2',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Terbot-2',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'March 25, 2020',
  },
  {
    name: 'Termitebot',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Termitebot',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: null,
    private: false,
    created_at: 'December 18, 2019',
  },
  {
    name: 'testDiscordBot',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/testDiscordBot',
    archived: false,
    stargazers_count: 0,
    language: 'JavaScript',
    license: null,
    private: false,
    created_at: 'April 07, 2020',
  },
  {
    name: 'tlib',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/tlib',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: null,
    private: false,
    created_at: 'December 13, 2019',
  },
  {
    name: 'typeschemalib',
    description:
      'A yaml like schema that can be used to check dictionaries for correct schema',
    html_url: 'https://github.com/JakeRoggenbuck/typeschemalib',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'September 20, 2020',
  },
  {
    name: 'ursina',
    description: 'A game engine powered by python and panda3d.',
    html_url: 'https://github.com/JakeRoggenbuck/ursina',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'March 28, 2021',
  },
  {
    name: 'ursina-platform-game',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/ursina-platform-game',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'March 29, 2021',
  },
  {
    name: 'valueourminds_website',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/valueourminds_website',
    archived: false,
    stargazers_count: 0,
    language: 'CSS',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 07, 2020',
  },
  {
    name: 'vim-character-creator',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/vim-character-creator',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 08, 2020',
  },
  {
    name: 'vim-game-snake',
    description: 'Vim Game : Snake',
    html_url: 'https://github.com/JakeRoggenbuck/vim-game-snake',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 02, 2020',
  },
  {
    name: 'vim-impulse-syntax',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/vim-impulse-syntax',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 02, 2020',
  },
  {
    name: 'vim-selection-test',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/vim-selection-test',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 09, 2020',
  },
  {
    name: 'vim-snow-script-syntax',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/vim-snow-script-syntax',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 09, 2020',
  },
  {
    name: 'vimage.vim',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/vimage.vim',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 26, 2020',
  },
  {
    name: 'Vorahk',
    description: 'A bot that sends my spotify playlists to bots to play them',
    html_url: 'https://github.com/JakeRoggenbuck/Vorahk',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'May 27, 2020',
  },
  {
    name: 'Vyxal',
    description:
      'A golfing language that has aspects of traditional programming languages.',
    html_url: 'https://github.com/JakeRoggenbuck/Vyxal',
    archived: false,
    stargazers_count: 0,
    language: null,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 23, 2021',
  },
  {
    name: 'wallpaper_downloader',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/wallpaper_downloader',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'June 03, 2020',
  },
  {
    name: 'xdotool_python_window_util',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/xdotool_python_window_util',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'July 29, 2020',
  },
  {
    name: 'yaml_serialize',
    description: 'A simple way to store python objects in yaml',
    html_url: 'https://github.com/JakeRoggenbuck/yaml_serialize',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'October 10, 2020',
  },
  {
    name: 'yes-no-neural-network-classifier',
    description: null,
    html_url:
      'https://github.com/JakeRoggenbuck/yes-no-neural-network-classifier',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'October 24, 2020',
  },
  {
    name: 'Yutimim-dictionary-parser',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/Yutimim-dictionary-parser',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: null,
    private: false,
    created_at: 'September 11, 2021',
  },
  {
    name: 'zerOS',
    description: 'an os? based on arch',
    html_url: 'https://github.com/JakeRoggenbuck/zerOS',
    archived: false,
    stargazers_count: 0,
    language: 'Shell',
    license: null,
    private: false,
    created_at: 'July 21, 2020',
  },
  {
    name: 'zflat',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/zflat',
    archived: false,
    stargazers_count: 0,
    language: 'C++',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'March 25, 2021',
  },
  {
    name: 'zflat.vim',
    description: null,
    html_url: 'https://github.com/JakeRoggenbuck/zflat.vim',
    archived: false,
    stargazers_count: 0,
    language: 'Vim script',
    license: {
      key: 'gpl-3.0',
      name: 'GNU General Public License v3.0',
      spdx_id: 'GPL-3.0',
      url: 'https://api.github.com/licenses/gpl-3.0',
      node_id: 'MDc6TGljZW5zZTk=',
    },
    private: false,
    created_at: 'March 25, 2021',
  },
  {
    name: 'zipfs-law',
    description: 'An example use of the library plrs',
    html_url: 'https://github.com/JakeRoggenbuck/zipfs-law',
    archived: false,
    stargazers_count: 0,
    language: 'Python',
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz',
    },
    private: false,
    created_at: 'August 31, 2021',
  },
];

var projects_data = [
  {
    name: 'QME Games',
    desc: 'Project Manager for the QME Games group',
    url: 'https://github.com/qmegame/',
  },
  {
    name: 'Software Club',
    desc: 'President of a club dedicated to teaching members of the DVCA High School how to write useful software and prepare for industry.',
    url: 'https://jr0.org/software-club.html',
  },
  {
    name: 'DHS Gamedev',
    desc: 'Project Manager for the DHS game development club',
    url: 'https://github.com/dhs-gamedev/',
  },
  {
    name: 'DHS Coding Club',
    desc: 'Project Manager for the DHS Coding Club',
    url: 'https://github.com/dhs-gamedev/',
  },
  {
    name: 'DV-CSHS',
    desc: 'The Da Vinci Computer Science website',
    url: 'https://sites.google.com/djusdstudents.org/dv-cshs',
  },
  {
    name: 'Citrus Circuits',
    desc: 'A high school robotics team',
    url: 'https://www.citruscircuits.org/',
  },
  {
    name: 'Server',
    desc: 'A data analysis project for the Citrus Circuits robotics team',
    url: 'https://github.com/JakeRoggenbuck/server-public',
  },
];

var links_data = [
  {
    name: 'Github',
    desc: 'The place with all my public programming projects',
    url: 'https://github.com/jakeroggenbuck',
  },
];

var tutoring_data = [
  {
    name: 'Intro to Python',
    description:
      'Learn the basics of programming with the Python Language. Learn variables, functions, control flow and more. The approach to learning in this class is applicable when learning any language or programming skill and is and amazing way to start.',
    prerequisites: [],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
    recommended: true,
  },
  {
    name: 'Intermediate Python',
    description:
      'Learn problem solving and algorithms in Python. The implementation of algorithms is one of the most sought-after skill in the industry.',
    prerequisites: ['Intro to python'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Advanced Python',
    description:
      "Learn advanced programming topics through the use of Python and it's many libraries.",
    prerequisites: ['Intermediate Python'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intro to Javascript',
    description:
      'Learn the basics of programming in Javascript. Javascript is the most popular language, and has tons of uses in the Web. Javascript is used in lots of places in learning and industry.',
    prerequisites: [],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
    recommended: true,
  },
  {
    name: 'Intermediate Javascript',
    description:
      'Javascript is an amazing language when learned correctly. This class will be expanding on ideas from the intro class to perfect skills with Javascript.',
    prerequisites: ['Intro to Javascript'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intro to Rust',
    description:
      'Learn the basics of programming in Rust. Rust is one of the fastest growing languages, with great reasons to learn it.',
    prerequisites: [],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intermediate Rust',
    description: 'Learn more complex ideas about algorithms in Rust.',
    prerequisites: ['Intro to Rust'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intro to C++',
    description:
      'An introduction to a great, modern systems level language. As one of the most used languages of programs and operating system, C++ is a great language to learn.',
    prerequisites: [],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intermediate C++',
    description:
      'A more in-depth look into the ideas about optimization and memory.',
    prerequisites: ['Intro to C++'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
  {
    name: 'Intro to Java',
    description:
      'Java continues to be extremely relevant, and a great way to learn programming, having uses in game development, and system level software, as well as being used by lots of notable Robotics teams.',
    prerequisites: [],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R, Cameron B'],
  },
  {
    name: 'Intermidiate to Java',
    description:
      'Java is one of the best languages for learning. Java can be used for all sorts of things in industry and is a great language to learn complex ideas with. Learn about classes, objects, polymorphism and more in the Intermediate class.',
    prerequisites: ['Intro to Java'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R, Cameron B'],
  },
  {
    name: 'APIs and Web Frameworks',
    description:
      'APIs and Web Frameworks are extremely important to the web, and continue to grow in importance. This class will teach things like Python Flask, FastAPI, and requests.',
    prerequisites: ['Intro to Python or Intro to Rust'],
    times_available: [],
    url: 'https://forms.gle/WGMkphCnRN56fKc96',
    teachers: ['Jake R'],
  },
];
