baseURL = 'https://jr0.org'
languageCode = 'en-us'
title = 'JR0.org'
theme = "gokarna"

[params]
  footer = "Jake Roggenbuck"
  avatarUrl = "/images/35516367.jpg"
  avatarSize = "size-m"
  description = "Software Developer & Student"

  customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  '''

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/jake-roggenbuck-1500a8215/"},
    {name = "dribbble", url = "https://jr0.org"},
    {name = "email", url = "mailto:me@jr0.org"},
    {name = "github", url = "https://github.com/jakeroggenbuck"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
	weight = 1

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Research"
    pre = "<span data-feather='book'></span>"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "Devlog"
    pre = "<span data-feather='book'></span>"
    url = "/devlogs/"
    weight = 4

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/jakeroggenbuck/JakeRoggenbuck.github.io"
    weight = 5

