#!/bin/bash

#     _            _         
#    | | __ _ _ __| |__  ___ 
# _  | |/ _` | '__| '_ \/ __|
#| |_| | (_| | |  | |_) \__ \
# \___/ \__,_|_|  |_.__/|___/

# Jake Auto Rice Bash Script


#Gets needed file from github
git clone https://github.com/JakeRoggenbuck/ConfigFiles ~/Downloads/ConfigFiles
git clone https://github.com/JakeRoggenbuck/.scripts.git ~/.scripts 

#Removes and adds dirs
rm -ri ~/Desktop

mv ~/Templates ~/.templates

mkdir ~/Repos
mkdir ~/Library

mkdir ~/Media

mv ~/Pictures ~/Media
mv ~/Music ~/Media
mv ~/Videos ~/Media

#Moves needed config files
cd ~/Downloads/ConfigFiles
mv bspwm/ ~/.config/     
mv sxhkd/ ~/.config/     
mv polybar/ ~/.config/ 
mv dunst/ ~/.config/     
mv rofi/ ~/.config/
mv nvim/ ~/.config/
mv vim/ ~/.config/
mv alacritty/ ~/.config/
mv termite/ ~/.config/

mkdir --parents /usr/share/xfce4/terminal/colorschemes/; mv xfce4TerminalColorSchemes/* $_

mv user-dirs.dirs ~/.config

mv .bashrc ~/
mv .bash_aliases ~/
mv .xscreensaver ~/
mv .profile ~/
mv .wallpaper/ ~/
