#!/bin/bash
#Gets needed file from github
git clone https://github.com/JakeRoggenbuck/ConfigFiles ~/Downloads/ConfigFiles
git clone https://github.com/JakeRoggenbuck/.scripts.git ~/.scripts 

#Removes and adds dirs
rm -ri ~/Desktop

mv ~/Templates ~/.templates

mkdir ~/Repos
mkdir ~/Resources

mkdir ~/Media

mv ~/Pictures ~/Media
mv ~/Music ~/Media
mv ~/Videos ~/Media

#Moves needed config files
cd ~/Downloads/ConfigFiles
mv bspwm/ ~/.config/     
mv sxhkd/ ~/.config/     
mv polybar/ ~/.config/ 
mv dunst/ ~/.config/     
mv rofi/ ~/.config/
mv nvim/ ~/.config/
mv vim/ ~/.config/

mv .bashrc ~/
mv .profile ~/
mv .wallpapers/ ~/

#Installs programs from array
bins=(neovim vim emacs feh eog ranger sxhkd bspwm polybar compton xfce4-terminal gimp kate firefox atom lxappearance ffmpeg dmenu rofi neofetch gnome-tweaks)

for x in "${bins[@]}" 
do	
	echo Do you want $x? y/n
	read answere

	if [ $answere == 'y' ]
	then
		pacman -S $x || echo installing $x failed
	fi
done

