.\" Manpage for Rusnote.
.\" Contact jake@jr0.org to correct errors or typos.
.TH man 8 "25 Dec 2019" "1.0" "rushnote man page"
.SH NAME
rushnote \- take quick notes from command line 
.SH SYNOPSIS
rushnote [OPTION]... [NOTE]...
.SH DESCRIPTION
A fast way to take quick and concise notes all from the command line. Create to-dos and task lists. 
.SH OPTIONS
-a	adds NOTE to save file
.br
-s	lists save file to command line
.br
-e	opens save file in editor
.SH BUG
if flags are not passed to rushnote, rushnote errors out and closes
.SH AUTHOR
Jake Roggenbuck, jake@jr0.org
